### ISSUE TITLE
Nieuwe quote: "A's ge het nie' wit, ken'de het 'ok behangen!"

### ISSUE THREAD

**Issue by dvanderleest** [cedricfortuin/hanquotes#1]
Als je vragen hebt, neem contact op met Cedric: [cl.fortuin@student.han.nl](mailto:cl.fortuin@student.han.nl)

Pulle requests inschieten is niet mogelijk

**Comment by cedricfortuin** [comment]
Hi Douwe! Tof dat je een nieuwe quote hebt :D. Hij wordt direct toegevoegd. :)
